In [115]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [116]:
iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species']=iris.target # coluna alvo

In [117]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [118]:
df.tail() # carrega as ultimas 5 linhas

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [119]:
df.shape # quantas linhas e colunas

(150, 5)

In [120]:
df.dtypes # que tipo de dados tem cada coluna

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
species                int64
dtype: object

In [121]:
df.describe() 
# resumo estatístico de todas as 
# colunas numéricas (média, desvio, padrão, mínimo, máximo)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [122]:
df['species'].value_counts() # contar cada classe

species
0    50
1    50
2    50
Name: count, dtype: int64

In [123]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

In [124]:
setosa = df[df['species'] == 0]
virginica = df[df['species'] == 2]

In [125]:
setosa['petal length (cm)'].mean()

np.float64(1.4620000000000002)

In [126]:
virginica['petal length (cm)'].mean()

np.float64(5.5520000000000005)

In [127]:
len(df[df['petal length (cm)'] > 5])

42

In [128]:
X = df.drop('species', axis=1) # tudo menos a coluna alvo
y = df['species'] # só a coluna alvo
print(X.shape, y.shape)

(150, 4) (150,)

In [129]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [130]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [131]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
# test_size=0.2 significa 20% para teste
# random_state=42 garante que o resultado é sempre igual
# sem random_state o split seria diferente cada vez que corresse
print(X_train.shape, X_test.shape)

(120, 4) (30, 4)

In [132]:
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)
y_pred = modelo.predict(X_test)
print(y_pred[:10]) # mostrar as primeiras 10 previsões

[1 0 2 1 1 0 1 2 1 1]

In [133]:
print(y_test.values[:10]) # mostra os primeiros 10 valores reais

[1 0 2 1 1 0 1 2 1 1]

In [134]:
modelo.predict([[5.1, 3.5, 1.4, 0.2]])

/home/petunia/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [135]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [136]:
modelo.predict([[6.7, 3.1, 5.6, 2.4]])

/home/petunia/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([2])

In [137]:
accuracy_score(y_test, y_pred) # calcula a accuracy

1.0

In [138]:
acc=accuracy_score(y_test, y_pred)
print(f'Accuracy: {acc:.2%}')

Accuracy: 100.00%

In [139]:
total_test = len(X_test)
flores_erradas = total_test * (1 - acc)
print(flores_erradas)

0.0

In [141]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

In [146]:
modelo2 = DecisionTreeClassifier(max_depth=3, random_state=42)
modelo2.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [145]:
y_pred2 = modelo2.predict(X_test)
print(accuracy_score(y_test, y_pred2))

1.0

In [147]:
modelo3 = DecisionTreeClassifier(max_depth=1, random_state=42)
modelo3.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=1, random_state=42)

In [149]:
y_pred3 = modelo3.predict(X_test)
print(accuracy_score(y_test, y_pred3))

0.6333333333333333

In [148]:
modelo4 = DecisionTreeClassifier(random_state=42)
modelo4.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [152]:
y_pred4 = modelo.predict(X_test)
print(accuracy_score(y_test, y_pred4))

1.0