In [1]:
print('Olá mundo')

Olá mundo

In [ ]:
import pandas as pd # biblioteca para trabalhar com dados em tabela
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [6]:
# criar um DataFrame
data = {
    'nome': ['Rosa', 'Violeta', 'Margarida'],
    'altura_cm': [30, 15, 25],
    'cor': ['vermelho', 'roxo', 'branco']
}
df = pd.DataFrame(data)
df # escrever só df mostra a tabela formatada

        nome  altura_cm       cor
0       Rosa         30  vermelho
1    Violeta         15      roxo
2  Margarida         25    branco

In [9]:
df.shape # (3 /** linhas */, 3 /** colunas */)

(3, 3)

In [11]:
data1 = {
    'cidade': ['Lisboa', 'Porto', 'Braga'],
    'altitude': [2, 85, 190],
    'temperatura': [17.5, 15.2, 14.1]
}
df = pd.DataFrame(data1)
df

   cidade  altitude  temperatura
0  Lisboa         2         17.5
1   Porto        85         15.2
2   Braga       190         14.1

In [12]:
df.shape

(3, 3)

In [ ]:
# carregar o iris
iris = datasets.load_iris()

# transformar em DataFrame
df = pd.DataFrame()